In [2]:
import numpy as np



In [2]:
a=np.array([1,3,4,5,6])

In [3]:
a


array([1, 3, 4, 5, 6])

In [4]:
type (a)

numpy.ndarray

In [5]:
a.shape

(5,)

In [6]:
# dimension
a.ndim

1

In [7]:
# two dimensional arry
b=np.array([[1,2,3,4,5],
            [2,3,4,5,6]])


In [8]:
type(b)

numpy.ndarray

In [9]:
b.shape

(2, 5)

In [10]:
b.ndim

2

In [11]:
c=np.array([[[1,2,3],[2,3,4],[1,3,2]]])
d=np.array([[[1,3,4],[1,2,4],[4,5,6]],
          [[1,2,3],[2,3,4],[6,7,8]]])

In [12]:
c


array([[[1, 2, 3],
        [2, 3, 4],
        [1, 3, 2]]])

In [13]:
d

array([[[1, 3, 4],
        [1, 2, 4],
        [4, 5, 6]],

       [[1, 2, 3],
        [2, 3, 4],
        [6, 7, 8]]])

In [14]:
c.shape

(1, 3, 3)

In [15]:
d.shape

(2, 3, 3)

In [16]:
a.dtype

dtype('int32')

In [17]:
c.dtype

dtype('int32')

In [18]:
# array element
a.size,b.size,c.size,d.size

(5, 10, 9, 18)

In [19]:
# how many memory consume 
a.nbytes,a.nbytes,c.nbytes,d.nbytes

(20, 20, 36, 72)

In [20]:
import numpy as np

In [21]:
a=np.array([1,3,4,5,6])
b=np.array([[1,2,3],[2,3,4]])
c=np.array([[[1,2,3],[1,2,3],[1,4,5]]])
d=np.array([[[1,3,4],[2,3,2],[1,2,4]],[[1,5,6],[5,3,2],[1,4,6]]])


In [22]:
type(a),a.ndim,a.size,a.shape,a.nbytes


(numpy.ndarray, 1, 5, (5,), 20)

In [23]:
type(b),b.shape,b.ndim,b.size,b.nbytes

(numpy.ndarray, (2, 3), 2, 6, 24)

In [24]:
type(c),c.shape,c.ndim,c.nbytes,c.size

(numpy.ndarray, (1, 3, 3), 3, 36, 9)

In [25]:
type(d),d.shape,d.size,d.ndim,d.nbytes,d

(numpy.ndarray,
 (2, 3, 3),
 18,
 3,
 72,
 array([[[1, 3, 4],
         [2, 3, 2],
         [1, 2, 4]],
 
        [[1, 5, 6],
         [5, 3, 2],
         [1, 4, 6]]]))

In [26]:
# array creation
arange=np.arange(1,10,2)
# its works likes loop which start from 1 and end in before 10 
# and with 2 number difference 


In [27]:
arange

array([1, 3, 5, 7, 9])

In [28]:
empty=np.empty((1,5))
empty

array([[4.24399158e-314, 8.48798317e-314, 4.24399158e-314,
        8.48798317e-314, 1.27319747e-313]])

In [29]:
for i in range(5):
    empty[:,i]=i
empty    

array([[0., 1., 2., 3., 4.]])

In [30]:
# array indexing and slicing
# indexing form 0,1,2,3.....continue
arr1=[1,2,3,4,5]
print(arr1)



[1, 2, 3, 4, 5]


In [31]:
arr1[1]

2

In [32]:
arr1[4]

5

In [33]:
# reverse indexing -1 is last one
arr1[-1],arr1[-2]


(5, 4)

In [34]:
arr2=np.random.randint(1,10,size=(3,3)) 
# random array with size

In [35]:
arr2

array([[9, 1, 1],
       [1, 7, 9],
       [8, 1, 9]])

In [36]:
# row column duitai 0 theke suru hoy
# find the array value
arr2[0][1]


1

In [37]:
# 3d dimensional random array
arr3=np.random.randint(1,10,size=(2,3,3))
# 2 for number  of matrix

In [38]:
arr3

array([[[7, 1, 2],
        [9, 5, 3],
        [6, 7, 7]],

       [[2, 9, 3],
        [4, 1, 2],
        [9, 2, 5]]])

In [39]:
# same ekhaneo 0 theke indexing
arr3[1][1][1]

1

In [40]:
# slicing
print(arr1)

[1, 2, 3, 4, 5]


In [41]:
# array theke kicu value niyer process hocce slicing
arr1[0:3]
# it's limit upto 3

[1, 2, 3]

In [42]:
arr1[1:4]

[2, 3, 4]

In [43]:
print (arr2)

[[9 1 1]
 [1 7 9]
 [8 1 9]]


In [44]:
arr2[0:2,0:2]
# first section for row and second section for coloum

array([[9, 1],
       [1, 7]])

In [45]:
arr2[1:,1:]

array([[7, 9],
       [1, 9]])

In [46]:
arr2[1:,0:2]

array([[1, 7],
       [8, 1]])

In [47]:
arr3

array([[[7, 1, 2],
        [9, 5, 3],
        [6, 7, 7]],

       [[2, 9, 3],
        [4, 1, 2],
        [9, 2, 5]]])

In [48]:
arr3[1,0:2,0:2]
# 1 for number of metrix and 0:2 for row and 0:2 for coloum

array([[2, 9],
       [4, 1]])

In [49]:
arr3[1,0:2,1:3]

array([[9, 3],
       [1, 2]])

In [114]:
# manipulated array shape
a=np.array ([[1,2,3],[2,3,4]])
a

array([[1, 2, 3],
       [2, 3, 4]])

In [115]:
a.shape

(2, 3)

In [107]:
areshaped=np.reshape(a,(3,2))

In [108]:
areshaped.shape

(3, 2)

In [112]:
aresize=np.resize(a,(2,3))

In [113]:
aresize

array([[1, 2, 3],
       [2, 3, 4]])

In [118]:
# reval,flatten and defining array shift
arr6=np.random.randint(1,10,size=(2,3))


In [119]:
arr6

array([[4, 3, 9],
       [9, 5, 8]])

In [123]:
# ravel(arr6 k niye ekti 1D array creat korce )
a_ravel=np.ravel(arr6)

In [125]:
a_ravel.shape
a_ravel

array([4, 3, 9, 9, 5, 8])

In [126]:
a_ravel[0]

4

In [127]:
a_ravel[0]=3

In [ ]:
arr6
# dekha jacce j amar ravel a value change korar por main 
# array er value o change hocce 

array([[3, 9, 7],
       [4, 3, 7]])

In [ ]:
# flatter
arr6_flatter=a.flatten()

In [ ]:
arr6_flatter

array([1, 2, 3, 2, 3, 4])

In [ ]:
arr6_flatter[0]

1

In [ ]:
arr6_flatter[0]=4

In [ ]:
arr6_flatter

array([4, 2, 3, 2, 3, 4])

In [ ]:
arr6
# ekhane flatten a change korleo main array te kono change hoy nai

array([[3, 9, 7],
       [4, 3, 7]])

difining an array shape

In [ ]:
arr6.shape

(2, 3)

In [ ]:
arr6.shape=(3,2)

In [ ]:
arr6

array([[3, 9],
       [7, 4],
       [3, 7]])

![](img%20.png)<br>
<h5>staking<h5>


In [30]:
arr7=np.random.randint(1,10,size=(3,2))

In [31]:
arr7

array([[7, 8],
       [7, 2],
       [6, 7]])

In [90]:
a=np.resize(arr7,(3,3))

In [91]:
b=a*2


In [92]:
b

array([[ 8,  6,  6],
       [16,  6,  6],
       [ 8,  6,  6]])

In [96]:
np.hstack((a, b))
    # horizontal

array([[ 4,  3,  3,  8,  6,  6],
       [ 8,  3,  3, 16,  6,  6],
       [ 4,  3,  3,  8,  6,  6]])

In [100]:
np.concatenate((a,b),axis=1)
#same as horizontal

array([[ 4,  3,  3,  8,  6,  6],
       [ 8,  3,  3, 16,  6,  6],
       [ 4,  3,  3,  8,  6,  6]])

In [97]:
np.vstack((a,b))
# vertical

array([[ 4,  3,  3],
       [ 8,  3,  3],
       [ 4,  3,  3],
       [ 8,  6,  6],
       [16,  6,  6],
       [ 8,  6,  6]])

In [101]:
np.concatenate((a,b),axis=0)
# same as vertical

array([[ 4,  3,  3],
       [ 8,  3,  3],
       [ 4,  3,  3],
       [ 8,  6,  6],
       [16,  6,  6],
       [ 8,  6,  6]])

<h3>depth stack<h3>

In [102]:
np.dstack((a,b))
# row gula k alada kora 

array([[[ 4,  8],
        [ 3,  6],
        [ 3,  6]],

       [[ 8, 16],
        [ 3,  6],
        [ 3,  6]],

       [[ 4,  8],
        [ 3,  6],
        [ 3,  6]]])

In [131]:
rakib=np.random.randint(1,5,size=(3,3))
rakib

array([[2, 3, 2],
       [3, 4, 2],
       [3, 2, 2]])

<h1>statistics with numpy</h1>

In [3]:
stats=np.array([[1,2,3],[2,3,4]])
stats

array([[1, 2, 3],
       [2, 3, 4]])

In [5]:
np.min(stats)

1

In [6]:
np.max(stats)

4

<h1>determinant of matrix</h1>

In [34]:
arr8=np.array([4,2,3,5,6,7])
arr8

array([4, 2, 3, 5, 6, 7])

In [36]:
# np.linalg.det(arr8)

<h1>import data in numpy</h2>

array([2, 3, 4, 5, 6, 7])